name: Secure Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t my-secure-app:${{ github.run_number }} .
        docker tag my-secure-app:${{ github.run_number }} my-secure-app:latest
    
    - name: Run security scan
      run: |
        # Install Trivy
        sudo apt-get update
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy -y
        
        # Scan the image
        trivy image my-secure-app:latest
    
    - name: Test application
      run: |
        # Run container for testing
        docker run -d --name test-container -p 3000:3000 my-secure-app:latest
        sleep 10
        
        # Basic health check
        curl -f http://localhost:3000/health || exit 1
        
        # Stop test container
        docker stop test-container
        docker rm test-container
    
    - name: Push to Docker Hub
      # Only deploy from main branch
      if: github.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
        docker tag my-secure-app:${{ github.run_number }} ${{ secrets.DOCKERHUB_USERNAME }}/my-secure-app:${{ github.run_number }}
        docker tag my-secure-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-secure-app:latest
        
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-secure-app:${{ github.run_number }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-secure-app:latest
        
        docker logout